FROM ansibleplaybookbundle/apb-base:latest

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wLjAKbmFtZTogdmlydHVhbGl6YXRpb24KZGVzY3JpcHRpb246IEt1YmVWaXJ0\
IGluc3RhbGxlcgpiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRp\
c3BsYXlOYW1lOiBLdWJldmlydAogIGxvbmdEZXNjcmlwdGlvbjogfAogICAgIEt1YmVWaXJ0IGVu\
YWJsZXMgdGhlIG1pZ3JhdGlvbiBvZiBleGlzdGluZyB2aXJ0dWFsaXplZCB3b3JrbG9hZHMgZGly\
ZWN0bHkgaW50byB0aGUgZGV2ZWxvcG1lbnQgd29ya2Zsb3dzIHN1cHBvcnRlZCBieSBLdWJlcm5l\
dGVzLgoKICAgICBUaGlzIHByb3ZpZGVzIGEgcGF0aCB0byBtb3JlIHJhcGlkIGFwcGxpY2F0aW9u\
IG1vZGVybml6YXRpb24gYnk6CiAgICAgICAgIC0gU3VwcG9ydGluZyBkZXZlbG9wbWVudCBvZiBu\
ZXcgbWljcm9zZXJ2aWNlIGFwcGxpY2F0aW9ucyBpbiBjb250YWluZXJzIHRoYXQgaW50ZXJhY3Qg\
d2l0aCBleGlzdGluZyB2aXJ0dWFsaXplZCBhcHBsaWNhdGlvbnMuCiAgICAgICAgIC0gQ29tYmlu\
aW5nIGV4aXN0aW5nIHZpcnR1YWxpemVkIHdvcmtsb2FkcyB3aXRoIG5ldyBjb250YWluZXIgd29y\
a2xvYWRzIG9uIHRoZSBzYW1lIHBsYXRmb3JtLCB0aGVyZWJ5IG1ha2luZyBpdCBlYXNpZXIgdG8g\
ZGVjb21wb3NlIG1vbm9saXRoaWMgdmlydHVhbGl6ZWQgd29ya2xvYWRzIGludG8gY29udGFpbmVy\
cyBvdmVyIHRpbWUuCiAgZG9jdW1lbnRhdGlvblVybDogaHR0cHM6Ly9naXRodWIuY29tL2t1YmV2\
aXJ0L2t1YmV2aXJ0L2Jsb2IvbWFzdGVyL1JFQURNRS5tZAogIGltYWdlVXJsOiBodHRwczovL2Nk\
bi5wYnJkLmNvL2ltYWdlcy9INUd1dGQ3LnBuZwogIHByb3ZpZGVyRGlzcGxheU5hbWU6ICJSZWQg\
SGF0LCBJbmMuIgpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBEZWZh\
dWx0IGRlcGxveW1lbnQgcGxhbiBmb3Iga3ViZXZpcnQtYXBiIHVzaW5nIGV4aXN0aW5nCiAgICBt\
ZXRhZGF0YToKICAgICAgZGlzcGxheU5hbWU6IERlZmF1bHQKICAgICAgbG9uZ0Rlc2NyaXB0aW9u\
OiBUaGlzIHBsYW4gZGVwbG95cyBrdWJldmlydAogICAgZnJlZTogVHJ1ZQogICAgcGFyYW1ldGVy\
czoKICAgICAgLSB0aXRsZTogT3BlblNoaWZ0IEFkbWluIFVzZXIKICAgICAgICBuYW1lOiBhZG1p\
bl91c2VyCiAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgcmVxdWlyZWQ6IHRydWUKICAgICAg\
LSB0aXRsZTogT3BlblNoaWZ0IEFkbWluIFBhc3N3b3JkCiAgICAgICAgbmFtZTogYWRtaW5fcGFz\
c3dvcmQKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICByZXF1aXJlZDogdHJ1ZQogICAgICAg\
IGRpc3BsYXlfdHlwZTogcGFzc3dvcmQKICAgICAgLSBuYW1lOiB2ZXJzaW9uCiAgICAgICAgdGl0\
bGU6IFZlcnNpb24KICAgICAgICBkZWZhdWx0OiAwLjYuMAogICAgICAgIGVudW06IFsnMC42LjAn\
LCAnMC41LjAnLCAnMC40LjAnLCAnMC4zLjAnLCAnMC4yLjAnLCAnMC4xLjAnXQogICAgICAgIHR5\
cGU6IGVudW0KICAgICAgLSB0aXRsZTogUmVnaXN0cnkgVVJMCiAgICAgICAgbmFtZTogcmVnaXN0\
cnlfdXJsCiAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgIC0gdGl0bGU6IFJlZ2lzdHJ5IE5hbWVz\
cGFjZQogICAgICAgIG5hbWU6IHJlZ2lzdHJ5X25hbWVzcGFjZQogICAgICAgIHR5cGU6IHN0cmlu\
Zwo="


RUN yum install -y iptables wget \
    && yum clean all

### UPSTREAM ONLY ###
COPY requirements.yml /opt/ansible/requirements.yml
COPY download-templates.sh /usr/bin/download-templates
RUN mkdir /opt/apb/kubevirt-templates \
    && download-templates /opt/apb/kubevirt-templates

RUN ansible-galaxy install -r /opt/ansible/requirements.yml \
    && cp -r ./kubevirt-templates /etc/ansible/roles/kubevirt-ansible/roles/kubevirt/templates/
### UPSTREAM ONLY ###

COPY playbooks/* /opt/apb/actions/
COPY inventory /etc/ansible/hosts
RUN chmod -R g=u /opt/{ansible,apb} /etc/ansible/roles

USER apb
