FROM ansibleplaybookbundle/apb-base:galaxy

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGt1YmV2aXJ0LWFwYgpkZXNjcmlwdGlvbjogQVBCIGZvciBtYW5h\
Z2luZyBLdWJlVmlydCBkZXBsb3ltZW50cwpiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFs\
Cm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBrdWJldmlydCAoQVBCKQogIGltYWdlVXJsOiBodHRw\
czovL2Nkbi5wYnJkLmNvL2ltYWdlcy9INUd1dGQ3LnBuZwpwbGFuczoKICAtIG5hbWU6IGRlZmF1\
bHQKICAgIGRlc2NyaXB0aW9uOiBEZWZhdWx0IGRlcGxveW1lbnQgcGxhbiBmb3Iga3ViZXZpcnQt\
YXBiCiAgICBtZXRhZGF0YToKICAgICAgZGlzcGxheU5hbWU6IERlZmF1bHQKICAgICAgbG9uZ0Rl\
c2NyaXB0aW9uOiBUaGlzIHBsYW4gcHJvdmlkZXMga3ViZXZpcnQKICAgIGZyZWU6IFRydWUKICAg\
IHBhcmFtZXRlcnM6CiAgICAgIC0gdGl0bGU6IE9wZW5zaGlmdCBBZG1pbiBVc2VyCiAgICAgICAg\
bmFtZTogYWRtaW5fdXNlcgogICAgICAgIHR5cGU6IHN0cmluZwogICAgICAgIHJlcXVpcmVkOiB0\
cnVlCiAgICAgIC0gdGl0bGU6IE9wZW5zaGlmdCBBZG1pbiBQYXNzd29yZAogICAgICAgIG5hbWU6\
IGFkbWluX3Bhc3N3b3JkCiAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgcmVxdWlyZWQ6IHRy\
dWUKICAgICAgICBkaXNwbGF5X3R5cGU6IHBhc3N3b3JkCiAgICAgIC0gbmFtZTogdGFnCiAgICAg\
ICAgdGl0bGU6IFRhZyB0byB1c2UKICAgICAgICB0eXBlOiBzdHJpbmcKICAgICAgICBkZWZhdWx0\
OiB2MC4zLjAKICAgICAgLSBuYW1lOiBzdG9yYWdlX3JvbGUKICAgICAgICB0aXRsZTogQmFja2Vu\
ZCBTdG9yYWdlCiAgICAgICAgZGVmYXVsdDogTm9uZQogICAgICAgIGVudW06IFsnTm9uZScsICdz\
dG9yYWdlLWNpbmRlcicsICdzdG9yYWdlLWRlbW8nLCAnc3RvcmFnZS1jbnMnXQogICAgICAgIHR5\
cGU6IGVudW0K"


ENV APB_ACTION_PATH="kubevirt-ansible/playbooks/kubevirt.yml"
COPY requirements.yml /opt/ansible/requirements.yml

RUN ansible-galaxy install -r /opt/ansible/requirements.yml
RUN chmod -R g=u /opt/{ansible,apb} /etc/ansible/roles

USER apb
